#if !defined(AFX_DRAWCTL_H__29DC9F80_5706_11D0_9899_00C04FD7D06E__INCLUDED_)
#define AFX_DRAWCTL_H__29DC9F80_5706_11D0_9899_00C04FD7D06E__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDrawCtl wrapper class

class CDrawCtl : public CWnd
{
protected:
    DECLARE_DYNCREATE(CDrawCtl)
public:
    CLSID const& GetClsid()
    {
        static CLSID const clsid
            = { 0x48ddcc1d, 0x1fe0, 0x11d0, { 0xb9, 0x1b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0 } };
        return clsid;
    }
    virtual BOOL Create(LPCTSTR /* lpszClassName */,
        LPCTSTR lpszWindowName, DWORD dwStyle,
        const RECT& rect,
        CWnd* pParentWnd, UINT nID,
        CCreateContext* /* pContext = NULL */)
    { return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
        const RECT& rect, CWnd* pParentWnd, UINT nID,
        CFile* pPersist = NULL, BOOL bStorage = FALSE,
        BSTR bstrLicKey = NULL)
    { return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
        pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
    void Connect(LPCTSTR pMachineName);
    void Disconnect();
    void Clear();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DRAWCTL_H__29DC9F80_5706_11D0_9899_00C04FD7D06E__INCLUDED_)
