# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (c) Microsoft Corporation.  All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and related
# electronic documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

AFXDLL=1
PROJ=MFCBIND
OBJS=	binddoc.obj bindview.obj cntritem.obj mainfrm.obj \
	mfcbind.obj objview.obj

USES_OLE=1

!include <mfcsamps.mak>

