//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::SDKSample::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::SDKSample::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->LayoutRoot = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 3:
        {
            this->ContentRoot = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 4:
        {
            this->MainScrollViewer = safe_cast<::Windows::UI::Xaml::Controls::ScrollViewer^>(__target);
        }
        break;
    case 5:
        {
            this->Footer = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 6:
        {
            this->FooterPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
        }
        break;
    case 7:
        {
            ::Windows::UI::Xaml::Controls::HyperlinkButton^ element7 = safe_cast<::Windows::UI::Xaml::Controls::HyperlinkButton^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::HyperlinkButton^>(element7))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Footer_Click);
        }
        break;
    case 8:
        {
            ::Windows::UI::Xaml::Controls::HyperlinkButton^ element8 = safe_cast<::Windows::UI::Xaml::Controls::HyperlinkButton^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::HyperlinkButton^>(element8))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Footer_Click);
        }
        break;
    case 9:
        {
            ::Windows::UI::Xaml::Controls::HyperlinkButton^ element9 = safe_cast<::Windows::UI::Xaml::Controls::HyperlinkButton^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::HyperlinkButton^>(element9))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Footer_Click);
        }
        break;
    case 10:
        {
            this->FeatureName = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 11:
        {
            this->ScenarioListLabel = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 12:
        {
            this->Scenarios = safe_cast<::Windows::UI::Xaml::Controls::ListBox^>(__target);
        }
        break;
    case 13:
        {
            this->DescriptionText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 14:
        {
            this->InputSection = safe_cast<::Windows::UI::Xaml::Controls::UserControl^>(__target);
        }
        break;
    case 15:
        {
            this->StatusBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 16:
        {
            this->OutputSection = safe_cast<::Windows::UI::Xaml::Controls::UserControl^>(__target);
        }
        break;
    case 17:
        {
            this->WindowsLogo = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
        }
        break;
    case 18:
        {
            this->FullScreenLandscape = safe_cast<::Windows::UI::Xaml::VisualState^>(__target);
        }
        break;
    case 19:
        {
            this->Filled = safe_cast<::Windows::UI::Xaml::VisualState^>(__target);
        }
        break;
    case 20:
        {
            this->FullScreenPortrait = safe_cast<::Windows::UI::Xaml::VisualState^>(__target);
        }
        break;
    case 21:
        {
            this->Snapped = safe_cast<::Windows::UI::Xaml::VisualState^>(__target);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::SDKSample::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


