# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (c) Microsoft Corporation.  All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and related
# electronic documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=CMNCTRL1
OBJS=datetime.obj monthcal.obj animctrl.obj cmnctrl1.obj mtreectl.obj \
	toolbar1.obj toolbar2.obj toolpage.obj treecpg.obj notifwdw.obj \
	propsht.obj

!include <mfcsamps.mak>
