
# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (c) Microsoft Corporation.  All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and Microsoft
# QuickHelp and/or WinHelp documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=DBVList
OBJS=empview.obj mainfrm.obj DBVList.obj DBVListDoc.obj \
	DBVListSet.obj DBVListView.obj

!include <mfcsamps.mak>
