# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (c) Microsoft Corporation.  All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and related
# electronic documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=TRACKER
OBJS=trackapp.obj trackdoc.obj trackvw.obj mainfrm.obj dialogs.obj

!if "$(PLATFORM)" == "M68K" || "$(PLATFORM)" == "MPPC"
MACPROJ=Tracker
MACSIG=TRAK
!endif

!include <mfcsamps.mak>
