# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (c) Microsoft Corporation.  All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and related
# electronic documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=COLLECT
OBJS=collect.obj collevw.obj mainfrm.obj colledoc.obj dwarryvw.obj \
	intlstvw.obj mapdwvw.obj mapssvw.obj ptarryvw.obj strlstvw.obj \
	typaryvw.obj typlstvw.obj typtrmap.obj

!if "$(PLATFORM)" == "M68K" || "$(PLATFORM)" == "MPPC"
MACPROJ=Collect
MACSIG=COLL
!endif

!include <mfcsamps.mak>
