# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (c) Microsoft Corporation.  All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and Microsoft
# QuickHelp and/or WinHelp documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=AUTOCLIK
ROOT=..\..\..
OBJS=autoclik.obj aclikdoc.obj aclikvw.obj mainfrm.obj childfrm.obj \
	dialogs.obj clikpnt.obj

USES_OLE=1

!include <mfcsamps.mak>
