# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (c) Microsoft Corporation.  All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and related
# electronic documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=IPDRIVE
OBJS=ipdrive.obj ipdridoc.obj ipdrivw.obj ipremote.obj mainfrm.obj
USES_OLE=1
EXTRA_LIBS=/subsystem:windows,4.0

!include <mfcsamps.mak>
