echo // MAKEHELP.BAT generated Help Map file.  Used by TSTCON.HPJ. >"hlp\TstCon.hm"
echo. >>"hlp\TstCon.hm"
echo // Commands (ID_* and IDM_*) >>"hlp\TstCon.hm"
makehm ID_,HID_,0x10000 IDM_,HIDM_,0x10000 resource.h >>"hlp\TstCon.hm"
echo. >>"hlp\TstCon.hm"
echo // Prompts (IDP_*) >>"hlp\TstCon.hm"
makehm IDP_,HIDP_,0x30000 resource.h >>"hlp\TstCon.hm"
echo. >>"hlp\TstCon.hm"
echo // Resources (IDR_*) >>"hlp\TstCon.hm"
makehm IDR_,HIDR_,0x20000 resource.h >>"hlp\TstCon.hm"
echo. >>"hlp\TstCon.hm"
echo // Dialogs (IDD_*) >>"hlp\TstCon.hm"
makehm IDD_,HIDD_,0x20000 resource.h >>"hlp\TstCon.hm"
echo. >>"hlp\TstCon.hm"
echo // Frame Controls (IDW_*) >>"hlp\TstCon.hm"
makehm IDW_,HIDW_,0x50000 resource.h >>"hlp\TstCon.hm"
