// File: TestCon.H
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
// This source code is only intended as a supplement to the
// Microsoft Classes Reference and related electronic
// documentation provided with the library.
// See these sources for detailed information regarding the
// Microsoft C++ Libraries products.

#import "TCProps.tlb"
using namespace TCPropsLib;

_COM_SMARTPTR_TYPEDEF( ICatInformation, __uuidof( ICatInformation ) );
_COM_SMARTPTR_TYPEDEF( IActiveScript, __uuidof( IActiveScript ) );
_COM_SMARTPTR_TYPEDEF( IActiveScriptParse, __uuidof( IActiveScriptParse ) );
_COM_SMARTPTR_TYPEDEF( IEnumCATEGORYINFO, __uuidof( IEnumCATEGORYINFO ) );
_COM_SMARTPTR_TYPEDEF( IEnumGUID, __uuidof( IEnumGUID ) );

#include "TstCon.H"
#include "TstConIF.H"
#include "TCTrace.H"
#include "OutWndVw.H"
#include "TCSplit.H"
#include "Log.H"
#include "MacroCB.H"
#include "MacroDB.H"
#include "AProp.H"
#include "TypeAttr.H"
#include "ExcepInf.H"
#include "VarUtils.H"
#include "PropBag.H"
#include "BindHost.H"
#include "MethInfo.H"
#include "MethodDg.H"
#include "MacroDg.H"
#include "MFileWnd.H"
#include "MainFrm.H"
#include "LogDg.H"
#include "RegCtlDg.H"
#include "ComCatDg.H"
#include "InsCtlDg.H"
#include "ExtCtl.H"
#include "TCItem.H"
#include "Script.H"
#include "ScrMngr.H"
#include "TCDoc.H"
#include "TCView.H"
#include "TabOrdDg.H"
#include "FeatPg.H"
#include "IFacesPg.H"
#include "ServPg.H"
#include "ConInfDg.H"
#include "NewAPDg.H"
#include "APropDg.H"
#include "EvLogPg.H"
#include "PChngPg.H"
#include "PEdReqPg.H"
#include "PBagDg.H"

