// stdafx.cpp : source file that includes just the standard includes
//  DBViewer.pch will be the pre-compiled header
//  stdafx.obj will contain the pre-compiled type information
//
// This is a part of the Microsoft Foundation Classes and
// Templates (MFC&T).
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
// This source code is only intended as a supplement to the
// MFC&T Reference and related electronic documentation provided
// with the library.  See these sources for detailed information
// regarding the MFC&T product.
//

#include "stdafx.h"

CComModule _Module;
