// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "drawctl.h"

/////////////////////////////////////////////////////////////////////////////
// CDrawCtl

IMPLEMENT_DYNCREATE(CDrawCtl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CDrawCtl properties

/////////////////////////////////////////////////////////////////////////////
// CDrawCtl operations

void CDrawCtl::Connect(LPCTSTR pMachineName)
{
    static BYTE parms[] =
        VTS_BSTR;
    InvokeHelper(0x60020000, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
         pMachineName);
}

void CDrawCtl::Disconnect()
{
    InvokeHelper(0x60020001, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CDrawCtl::Clear()
{
    InvokeHelper(0x60020002, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
