# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (c) Microsoft Corporation.  All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and related
# electronic documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=CMNCTRL2
OBJS=cmnctrl2.obj notifwdw.obj progctrl.obj propsht.obj slidctrl.obj \
	spinctrl.obj

!include <mfcsamps.mak>
