import "C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\prsht.idl";
import "C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\MsHTML.idl";
import "c:\program files (x86)\windows kits\10\include\10.0.15063.0\um\dimm.idl";
import "c:\program files (x86)\windows kits\10\include\10.0.15063.0\um\dispex.idl";
import "C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\dxgitype.idl";
import "c:\program files (x86)\windows kits\10\include\10.0.15063.0\shared\dxgicommon.idl";
import "c:\program files (x86)\windows kits\10\include\10.0.15063.0\shared\dxgiformat.idl";
import "C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\MsHtmHst.idl";
import "c:\program files (x86)\windows kits\10\include\10.0.15063.0\um\docobj.idl";
import "C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\ExDisp.idl";
import "C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\ObjSafe.idl";

[
	object,
	uuid(12BFAE1F-0BF9-4170-BE6E-31723B61C033),
	dual,
	helpstring("IATLAsyncAttrib Interface"),
	pointer_default(unique)
] 
#line 23 "c:\\temp\\vcsamples\\vc2010samples\\attributes\\advanced\\async\\atlasync.h"
interface IATLAsyncAttrib : IDispatch {
#line 25 "c:\\temp\\vcsamples\\vc2010samples\\attributes\\advanced\\async\\atlasync.h"
	[propput,id(0)] HRESULT  URL([in] BSTR strURL);
	[propget,id(0)] HRESULT  URL([out,retval] BSTR *pstrURL);
};


[ version(1.0), uuid(65358E88-155A-11D3-ABDF-00C04F797AB7) ]
library ASYNCATTRIBLib
{
	importlib("stdole2.tlb");
	importlib("olepro32.dll");

	[
		version(1.0),
		uuid(F447C21A-5F8C-4E88-B2D9-B76027CACFA5)
	] 
#line 42 "c:\\temp\\vcsamples\\vc2010samples\\attributes\\advanced\\async\\atlasync.h"
	coclass CATLAsyncAttrib {
		[default]	interface IATLAsyncAttrib;
	};

}

