; Listing generated by Microsoft (R) Optimizing Compiler Version 19.11.25507.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\ericmitt\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
