// File: atlduck.idl
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
// This source code is only intended as a supplement to the
// Microsoft Classes Reference and related electronic
// documentation provided with the library.
// See these sources for detailed information regarding the
// Microsoft C++ Libraries products.

import  "oaidl.idl";
// atlduck.idl : IDL source for atlduck.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (atlduck.tlb) and marshalling code.

	[
	
		uuid(120B729F-65BF-11D0-9DDC-00A0C9034892),
	
		helpstring("IDuckDoer Interface"),
		pointer_default(unique)
	]
	interface IDuckDoer : IUnknown
	{
	};
[
	uuid(120B7293-65BF-11D0-9DDC-00A0C9034892),
	version(1.0),
	helpstring("atlduck 1.0 Type Library")
]
library ATLDUCKLib
{
	importlib("stdole32.tlb");

	[
		uuid(120B72A0-65BF-11D0-9DDC-00A0C9034892),
		helpstring("DuckDoer Class")
	]
	coclass DuckDoer
	{
		[default,source] interface IDuckDoer;
	};
};
