# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (c) Microsoft Corporation.  All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and related
# electronic documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=MAKEHM
OBJS=makehm.obj makehm.res
CONSOLE=1
NO_PCH=1
UNICODE=0

!include <mfcsamps.mak>
