// mdichild.h
//
// This is a part of the Microsoft Foundation Classes C++ library.
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
// This source code is only intended as a supplement to the
// Microsoft Foundation Classes Reference and related
// electronic documentation provided with the library.
// See these sources for detailed information regarding the
// Microsoft Foundation Classes product.
//
// Purpose: interface of the CDynaMDIChildWnd class
//
// Functions:
//   Most of this file was generated by AppWizard.  The functions
//   which contain code specific to this sample are:
//
//      CDynaMDIChildWnd::OnMDIActivate()    -- handle activation/deactivation
//      CDynaMDIChildWnd::RefreshColorMenu() -- update Color submenu contents
//
//   These functions are implemented in mdichild.cpp.

/////////////////////////////////////////////////////////////////////////////
// CDynaMDIChildWnd frame

class CDynaMDIChildWnd : public CMDIChildWnd
{
	DECLARE_DYNCREATE(CDynaMDIChildWnd)
protected:
	CDynaMDIChildWnd();         // protected constructor used by dynamic creation

// Attributes
public:

// Operations
public:
	void RefreshColorMenu();

// Implementation
protected:
	virtual ~CDynaMDIChildWnd();

	// Generated message map functions
	//{{AFX_MSG(CDynaMDIChildWnd)
	afx_msg void OnMDIActivate(BOOL bActivate, CWnd* pActivateWnd, CWnd* pDeactivateWnd);
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};

/////////////////////////////////////////////////////////////////////////////
