# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (c) Microsoft Corporation.  All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and Microsoft
# QuickHelp and/or WinHelp documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.

PROJ=IVIEWERS
OBJS=dataobj.obj    dispatch.obj   guid.obj       iadvsink.obj   idataobj.obj   iviewer.obj   \
	 iviewers.obj   shadow.obj     tlblist.obj    tlbodl.obj     tlbtree.obj   \
	 tree.obj       typelib.obj    util.obj

USRDLL=1

!include <mfcsamps.mak>
